get:
  description: Get a specific entry by customer ID.
  parameters:
    - name: customer_id
      in: path
      type: integer
      required: true
      description: ID of the customer
  responses:
    200:
      description: List of entries from customer table.
      schema:
        type: object
        properties:
          datas:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the customer
                name:
                  type: string
                  description: Name of the customer
                email:
                  type: string
                  description: Email of the customer
                phone:
                  type: string
                  description: Phone number of the customer